### ISSUE TITLE
Laravel Integration Error. 

### ISSUE THREAD

**Issue by Christopher-Law** [resend/resend-laravel#49]
I have followed the defined instructions for Laravel-Resend and am seeing this error when attempting to send a raw email . 
TYPE ERROR  Symfony\Component\Mime\Header\Headers::addTextHeader(): Argument #2 ($value) must be of type string, null given,

**Comment by Christopher-Law** [comment]
Looks like X-Resend-Email-ID is null

**Comment by jayanratna** [comment]
Hey @Christopher-Law, I'll take a look at this issue and report back with a solution.

Thank you for reporting this 👌🏽

**Comment by jayanratna** [comment]
Could you please send through the code you used to send the email? Perhaps your Mailable class or API request payload for the Resend facade.

**Comment by Christopher-Law** [comment]
Sorry, I had to change providers.
