### ISSUE TITLE
Intermittent Syntax Error in ResendTransportFactory when Sending Emails

### ISSUE THREAD

**Issue by BrenoRibeiro706** [resend/resend-laravel#59]
### Description
We are experiencing an intermittent syntax error when attempting to send emails using the `ResendTransportFactory`. This issue does not occur on all requests, suggesting some conditionality in the error's appearance.

### Error Details
The error message is as follows:

}[2024-06-07 00:52:59] local.ERROR: Syntax error {"exception":"[object] (Exception(code: 0): Syntax error at vendor/resend/resend-laravel/src/Transport/ResendTransportFactory.php:73)
[stacktrace]

**File:** `resend-laravel/src/Transport/ResendTransportFactory.php`
**Line:** 73

### Occurrence
This error seems to be occurring randomly, as it does not appear with every email sending attempt. It might be related to specific conditions or data inputs that are not yet clearly identified.

### Steps to Reproduce
1. Initiate the email sending process through `ResendTransportFactory`.
2. Occasionally, the syntax error occurs without clear reproducibility patterns.

**Comment by jayanratna** [comment]
Hey @BrenoRibeiro706, I just released `v0.12.0`, could you check if that version fixes the issue?

I have updated the exception type from a regular `Exception` to a Symfony `TransportException`.

**Comment by BrenoRibeiro706** [comment]
The error no longer appears, thank you very much Jayan Ratna!
